update-initramfs ?

diff --git a/gentoo/usr/src/initramfs/init b/gentoo/usr/src/initramfs/init
--- a/gentoo/usr/src/initramfs/init
+++ b/gentoo/usr/src/initramfs/init
@@ -11,11 +11,9 @@ die() {
 echo "Beware, Inside there be Dragons!"
 
 # mount /proc, /sys and /dev
-echo -n "Mounting"
-mount -t proc none /proc && echo -n " /proc" || die "/proc mount failed."
-mount -t sysfs none /sys && echo -n " /sys" || die "/sys mount failed."
-mount -t devtmpfs none /dev && echo -n " /dev" || die "/dev mount failed."
-echo " done."
+mount -t proc none /proc || die "/proc mount failed."
+mount -t sysfs none /sys || die "/sys mount failed."
+mount -t devtmpfs none /dev || die "/dev mount failed."
 
 for PARAM in $(cat /proc/cmdline) ; do
 	case ${PARAM} in
@@ -26,10 +24,10 @@ for PARAM in $(cat /proc/cmdline) ; do
 	esac
 done
 
-echo -n "Searching for valid keys ... "
+echo "..."
 while ! (findfs UUID=48249452-e545-4a94-9da6-48e628368289 > /dev/null 2>&1); do sleep 1; done
 crypt_keystore=$(findfs UUID=48249452-e545-4a94-9da6-48e628368289)
-echo "found on ${crypt_keystore}"
+echo "Valid key found on ${crypt_keystore}"
 
 crypt_root=$(findfs UUID=78ad20f5-c609-4060-9f21-671fb0b7ee51)
 crypt_resume=$(findfs UUID=ac2e87c2-02dd-4396-b858-dd1849f60873)
@@ -38,13 +36,13 @@ crypt_misc=$(findfs UUID=e73a024a-74b7-45c5-85e9-10ef748d5b4d)
 cryptsetup luksOpen ${crypt_keystore} keystore -d /etc/keys/keystore.key
 mount -o ro /dev/mapper/keystore /mnt/keystore
 
-echo "Decrypting ${crypt_resume}"
+echo "Decrypting ${crypt_resume} ..."
 cryptsetup open ${crypt_resume} swap -d /mnt/keystore/swap.key
 
-echo "Decrypting ${crypt_root}"
+echo "Decrypting ${crypt_root} ..."
 cryptsetup luksOpen ${crypt_root} root -d /mnt/keystore/root.key
 
-echo "Decrypting ${crypt_misc}"
+echo "Decrypting ${crypt_misc} ..."
 cryptsetup luksOpen ${crypt_misc} storage -d /mnt/keystore/storage.key
 
 umount /mnt/keystore
@@ -53,10 +51,9 @@ cryptsetup close keystore
 resume="/dev/mapper/swap"
 root="/dev/mapper/root"
 
-echo "Trying to resume from ${resume}"
+echo "Trying to resume from hibernation ..."
 printf '%u:%u\n' $(stat -L -c '0x%t 0x%T' ${resume}) > /sys/power/resume || die "cannot resume"
 
-# Open the encrypted partitions
 mount -o rw ${root} /mnt/root || die "mounting /mnt/root failed."
 
 # Clean up
