update initramfs

diff --git a/gentoo/usr/src/initramfs/init b/gentoo/usr/src/initramfs/init
--- a/gentoo/usr/src/initramfs/init
+++ b/gentoo/usr/src/initramfs/init
@@ -11,13 +11,22 @@ die() {
 echo "Beware, Inside there be Dragons!"
 
 # mount /proc, /sys and /dev
-mount -t proc none /proc || die "/proc mount failed."
-mount -t sysfs none /sys || die "/sys mount failed."
-mount -t devtmpfs none /dev || die "/dev mount failed."
+echo -n "Mounting"
+mount -t proc none /proc && echo -n " /proc" || die "/proc mount failed."
+mount -t sysfs none /sys && echo -n " /sys" || die "/sys mount failed."
+mount -t devtmpfs none /dev && echo -n " /dev" || die "/dev mount failed."
+echo " done."
 
-echo "Searching for Keys..."
+for PARAM in $(cat /proc/cmdline) ; do
+	case ${PARAM} in
+		maintain)
+			echo "maintenance flag is enabled. dropping to a shell"
+			exec sh
+		;;
+	esac
+done
+
 while ! (findfs UUID=48249452-e545-4a94-9da6-48e628368289 > /dev/null 2>&1); do sleep 1; done
-
 crypt_keystore=$(findfs UUID=48249452-e545-4a94-9da6-48e628368289)
 echo "Key found on ${crypt_keystore}"
 
@@ -47,7 +56,7 @@ echo "Trying to resume from ${resume}"
 printf '%u:%u\n' $(stat -L -c '0x%t 0x%T' ${resume}) > /sys/power/resume || die "cannot resume"
 
 # Open the encrypted partitions
-mount -o "${mount_ro_rw}" ${root} /mnt/root || die "mounting /mnt/root failed."
+mount -o rw ${root} /mnt/root || die "mounting /mnt/root failed."
 
 # Clean up
 umount /proc
